services:
  paypalexampleapp:
    image: ${DOCKER_REGISTRY-}paypalexampleapp
    build:
      context: Application
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sql_server
  sql_server:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=strong_Password
